[
    {
        "id": 77708960,
        "name": "White House Hotel London",
        "starRating": 3.5,
        "urls": {},
        "address": {
            "streetAddress": "102 Sussex Gardens",
            "extendedAddress": "",
            "locality": "London",
            "postalCode": "W2 1UH",
            "region": "England",
            "countryName": "United Kingdom",
            "countryCode": "gb",
            "obfuscate": False,
        },
        "guestReviews": {
            "unformattedRating": 6.8,
            "rating": "6,8",
            "total": 79,
            "scale": 10,
            "badge": "good",
            "badgeText": "Хорошо",
        },
        "landmarks": [
            {"label": "Аэропорт Хитроу (LHR)", "distance": "20 км"},
            {"label": "Великобритания (аэропорт Гатуик-LGW)", "distance": "40 км"},
        ],
        "geoBullets": [],
        "ratePlan": {
            "price": {"current": "$73", "exactCurrent": 72.72, "old": "$74"},
            "features": {"paymentPreference": False, "noCCRequired": False},
        },
        "neighbourhood": "Паддингтон",
        "deals": {},
        "messaging": {},
        "badging": {},
        "pimmsAttributes": "DoubleStamps|D13|MESOTESTUK|TESCO",
        "coordinate": {"lat": 51.516304, "lon": -0.171327},
        "providerType": "MULTISOURCE",
        "supplierHotelId": 2397155,
        "isAlternative": False,
        "optimizedThumbUrls": {
            "srpDesktop": "https://exp.cdn-hotels.com/hotels/3000000/2400000/2397200/2397155/dad965ca_z.jpg?impolicy=fcrop&w=250&h=140&q=high"
        },
    },
    {
        "id": 285711,
        "name": "Linden House Hotel",
        "starRating": 3.0,
        "urls": {},
        "address": {
            "streetAddress": "4-6 Sussex Place",
            "extendedAddress": "Hyde Park",
            "locality": "London",
            "postalCode": "W2 2TP",
            "region": "England",
            "countryName": "United Kingdom",
            "countryCode": "gb",
            "obfuscate": False,
        },
        "guestReviews": {
            "unformattedRating": 6.6,
            "rating": "6,6",
            "total": 1039,
            "scale": 10,
            "badge": "good",
            "badgeText": "Хорошо",
        },
        "landmarks": [
            {"label": "Аэропорт Хитроу (LHR)", "distance": "20 км"},
            {"label": "Великобритания (аэропорт Гатуик-LGW)", "distance": "40 км"},
        ],
        "geoBullets": [],
        "ratePlan": {
            "price": {"current": "$79", "exactCurrent": 79.31},
            "features": {"paymentPreference": False, "noCCRequired": False},
        },
        "neighbourhood": "Паддингтон",
        "deals": {},
        "messaging": {},
        "badging": {},
        "pimmsAttributes": "DoubleStamps|D13|increaseNumberOfReviewsRequired",
        "coordinate": {"lat": 51.514502, "lon": -0.17291},
        "providerType": "MULTISOURCE",
        "supplierHotelId": 1951455,
        "isAlternative": False,
        "optimizedThumbUrls": {
            "srpDesktop": "https://exp.cdn-hotels.com/hotels/2000000/1960000/1951500/1951455/2bd1f19b_z.jpg?impolicy=fcrop&w=250&h=140&q=high"
        },
    },
    {
        "id": 140320,
        "name": "Park Avenue Bayswater Inn Hyde Park",
        "starRating": 4.0,
        "urls": {},
        "address": {
            "streetAddress": "8-16 Princes Square",
            "extendedAddress": "Bayswater",
            "locality": "London",
            "postalCode": "W2 4NT",
            "region": "England",
            "countryName": "United Kingdom",
            "countryCode": "gb",
            "obfuscate": False,
        },
        "guestReviews": {
            "unformattedRating": 6.0,
            "rating": "6,0",
            "total": 1676,
            "scale": 10,
            "badge": "good",
            "badgeText": "Хорошо",
        },
        "landmarks": [
            {"label": "Аэропорт Хитроу (LHR)", "distance": "18 км"},
            {"label": "Великобритания (аэропорт Гатуик-LGW)", "distance": "40 км"},
        ],
        "geoBullets": [],
        "ratePlan": {
            "price": {"current": "$98", "exactCurrent": 98.44},
            "features": {"paymentPreference": False, "noCCRequired": False},
        },
        "neighbourhood": "Бейсуотер",
        "deals": {},
        "messaging": {},
        "badging": {},
        "pimmsAttributes": "DoubleStamps|D13|TESCO",
        "coordinate": {"lat": 51.512944, "lon": -0.19218},
        "providerType": "MULTISOURCE",
        "supplierHotelId": 522132,
        "isAlternative": False,
        "optimizedThumbUrls": {
            "srpDesktop": "https://exp.cdn-hotels.com/hotels/1000000/530000/522200/522132/fef098f8_z.jpg?impolicy=fcrop&w=250&h=140&q=high"
        },
    },
    {
        "id": 140321,
        "name": "Wedgewood Hotel",
        "starRating": 2.5,
        "urls": {},
        "address": {
            "streetAddress": "49-51 Leinster Square",
            "extendedAddress": "Bayswater",
            "locality": "London",
            "postalCode": "W2 4PU",
            "region": "England",
            "countryName": "United Kingdom",
            "countryCode": "gb",
            "obfuscate": False,
        },
        "guestReviews": {
            "unformattedRating": 6.0,
            "rating": "6,0",
            "total": 1038,
            "scale": 10,
            "badge": "good",
            "badgeText": "Хорошо",
        },
        "landmarks": [
            {"label": "Аэропорт Хитроу (LHR)", "distance": "18 км"},
            {"label": "Великобритания (аэропорт Гатуик-LGW)", "distance": "40 км"},
        ],
        "geoBullets": [],
        "ratePlan": {
            "price": {"current": "$70", "exactCurrent": 70.12, "old": "$75"},
            "features": {"paymentPreference": False, "noCCRequired": False},
        },
        "neighbourhood": "Бейсуотер",
        "deals": {},
        "messaging": {},
        "badging": {},
        "pimmsAttributes": "DoubleStamps|D13|TESCO",
        "coordinate": {"lat": 51.513485, "lon": -0.192601},
        "providerType": "MULTISOURCE",
        "supplierHotelId": 115939,
        "isAlternative": False,
        "optimizedThumbUrls": {
            "srpDesktop": "https://exp.cdn-hotels.com/hotels/1000000/120000/116000/115939/f1df2d57_z.jpg?impolicy=fcrop&w=250&h=140&q=high"
        },
    },
    {
        "id": 285740,
        "name": "Nayland Hotel",
        "starRating": 3.0,
        "urls": {},
        "address": {
            "streetAddress": "132-134 Sussex Gardens",
            "extendedAddress": "",
            "locality": "London",
            "postalCode": "W2 1UB",
            "region": "England",
            "countryName": "United Kingdom",
            "countryCode": "gb",
            "obfuscate": False,
        },
        "guestReviews": {
            "unformattedRating": 6.8,
            "rating": "6,8",
            "total": 295,
            "scale": 10,
            "badge": "good",
            "badgeText": "Хорошо",
        },
        "landmarks": [
            {"label": "Аэропорт Хитроу (LHR)", "distance": "20 км"},
            {"label": "Великобритания (аэропорт Гатуик-LGW)", "distance": "40 км"},
        ],
        "geoBullets": [],
        "ratePlan": {
            "price": {"current": "$90", "exactCurrent": 89.89},
            "features": {"paymentPreference": False, "noCCRequired": False},
        },
        "neighbourhood": "Паддингтон",
        "deals": {},
        "messaging": {},
        "badging": {},
        "pimmsAttributes": "DoubleStamps|D13|TESCO",
        "coordinate": {"lat": 51.515368, "lon": -0.171928},
        "providerType": "MULTISOURCE",
        "supplierHotelId": 193579,
        "isAlternative": False,
        "optimizedThumbUrls": {
            "srpDesktop": "https://exp.cdn-hotels.com/hotels/1000000/200000/193600/193579/f63ece04_z.jpg?impolicy=fcrop&w=250&h=140&q=high"
        },
    },
]
